name: windows-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.*'
          cache: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'latest'

      - name: Configure
        run: cmake --preset windows_msvc

      - name: Build
        run: cmake --build --preset windows_msvc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IAMNXLAUNCHER-exe
          path: build/bin/   
